import Head from "next/head";
import { getAllTags, getNumberOfPages, getPostByPage } from "@/lib/notion-api";
import SinglePost from "@/components/post/single-post";
import Pagination from "@/components/pagination";
import Tag from "@/components/tag/tag";
import { AllTags, Post } from "@/types/Post";
import { GetStaticPropsContext } from "next";

export const getStaticPaths = async () => {
  const numberOfPage = await getNumberOfPages();

  let params = [];
  for (let i = 1; i <= numberOfPage; i++) {
    params.push({ params: { page: i.toString() } });
  }

  return {
    paths: params,
    fallback: "blocking",
  };
};

export const getStaticProps = async (context: GetStaticPropsContext) => {
  if (context.params === undefined) {
    throw new Error("context.params is undefined");
  }

  if (context.params.page === undefined) {
    throw new Error("context.params.page is undefined");
  }

  const currentPage = context.params.page;
  const postsByPage = await getPostByPage(parseInt(currentPage.toString(), 10));
  const numberOfPage = await getNumberOfPages();
  const allTags = await getAllTags();

  if (process.env.REVALIDATE_TIME === undefined) {
    throw new Error("REVALIDATE_TIME is not defined");
  }

  return {
    props: {
      postsByPage,
      numberOfPage,
      allTags,
      currentPage: parseInt(currentPage.toString(), 10),
    },
    revalidate: parseInt(process.env.REVALIDATE_TIME, 10),
  };
};

type Props = {
  postsByPage: Post[];
  numberOfPage: number;
  allTags: AllTags;
  currentPage: number;
};

export default function BlogPageList({
  postsByPage,
  numberOfPage,
  allTags,
  currentPage,
}: Props) {
  return (
    <div className="container h-full w-full mx-auto">
      <Head>
        <title>Notion-blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container w-full mt-16 mx-auto">
        <h1 className="text-5xl font-medium text-center mb-16">Blogs</h1>
        <section className="sm:grid grid-cols-2 w-5/6 gap-3 mx-auto">
          {postsByPage.map((post: Post) => (
            <div key={post.id}>
              <SinglePost
                title={post.title}
                description={post.description}
                date={post.date}
                tags={post.tags}
                slug={post.slug}
              />
            </div>
          ))}
        </section>
        <Pagination
          numberOfPage={numberOfPage}
          tag={""}
          currentPage={currentPage}
        />
        <Tag tags={allTags} />
      </main>
    </div>
  );
}
