import Head from "next/head";
import { getAllTags, getPostTopPage } from "../lib/notion-api";
import SinglePost from "../components/post/single-post";
import Link from "next/link";
import Tag from "../components/tag/tag";

export const getStaticProps = async () => {
  const allPosts = await getPostTopPage();
  const allTags = await getAllTags();

  return {
    props: {
      allPosts,
      allTags,
    },
    revalidate: 10,
  };
};

export default function Home({ allPosts, allTags }) {
  return (
    <div className="container h-full w-full mx-auto">
      <Head>
        <title>Notion-blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container w-full mt-16">
        <h1 className="text-5xl font-medium text-center mb-16">Notion Blog</h1>
        {allPosts.map((post) => (
          <div key={post.id} className="mx-4">
            <SinglePost
              title={post.title}
              description={post.description}
              date={post.date}
              tags={post.tags}
              slug={post.slug}
              isPagination={false}
            />
          </div>
        ))}

        <Link
          href="/posts/page/1"
          className="mb-6 lg:w-1/2 mx-auto px-5 block text-right"
        >
          ...もっと見る
        </Link>
        <Tag tags={allTags} />
      </main>
    </div>
  );
}
